#!/usr/bin/env bash

# get the full directory name of the script no matter where it is being called from
# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export DOCKER_STACK_DIR=$DIR/docker-clipper
export ROOT_DIR=$DIR

# Get IP address - only on OSX
IP=$(ipconfig getifaddr en0) #ethernet
if [ -z $IP]; then
    IP=$(ipconfig getifaddr en1) #wifi
fi

if [ -f .env ]; then
    source .env
fi

DOCKERCOMPOSE="docker-compose --file $DOCKER_STACK_DIR/docker-compose.yml"

if [ $# -gt 0 ]; then
    case $1 in
        install)
            echo "To the sea..."
            echo
            echo "Making executable script"
            chmod +x clipper
            # Building Docker stack
            ./clipper build
        ;;
        config)
            echo "check docker-compose file"
            $DOCKERCOMPOSE config
        ;;
        build)
            echo "build docker-compose"
            $DOCKERCOMPOSE build
        ;;
        start)
            echo "starting stack"
            $DOCKERCOMPOSE up -d
        ;;
        stop)
            echo "stopping stack"
            $DOCKERCOMPOSE down
        ;;
        composer)
            shift 1
            echo "composer $@"
            $DOCKERCOMPOSE exec php composer "$@"
        ;;
        bash)
            echo "exposing bash of php container"
            $DOCKERCOMPOSE exec php bash
        ;;
        npm)
            shift 1
            echo "npm $@"
            $DOCKERCOMPOSE run --rm node npm "$@"
        ;;
        watch)
            echo "npm run watch"
            $DOCKERCOMPOSE run --rm node npm run watch
        ;;
        nodebash)
            echo "node bash"
            $DOCKERCOMPOSE run --rm node bash
        ;;
        ip)
            echo "Front: "
            echo "http://localhost:${HTTP_PORT}"
            echo "http://$IP:$HTTP_PORT"
        ;;
        *)
            echo "Unknown command"
            exit 0
        ;;
    esac

else
    echo "You didn't type any command"
    exit 0
fi

exit 0